# ============================================================
# GENERATED BY SCXCODEX (scx-coder) via the Kritical SCX muxing/proxy stack, 2026-07-05.
# Syntax-validated (PowerShell AST parse: 0 errors). Reviewed before production use.
# Demonstrates SCXCodex building real D365 Sales deployment automation end to end.
# ============================================================
function Publish-KritD365SalesApp {
    <#
    .SYNOPSIS
        Publishes a D365 Sales app to a Business Central environment.

    .DESCRIPTION
        This function publishes a .app file to a Business Central environment.
        It uses BcContainerHelper if available, otherwise falls back to the BC Admin API.

    .EXAMPLE
        Publish-KritD365SalesApp -AppFile "C:\Apps\MySalesApp.app" -EnvironmentName "Production"

    .EXAMPLE
        Publish-KritD365SalesApp -AppFile "C:\Apps\MySalesApp.app" -EnvironmentName "Sandbox" -Tenant "mytenant" -Force

    .EXAMPLE
        Publish-KritD365SalesApp -AppFile "C:\Apps\MySalesApp.app" -EnvironmentName "Production" -CompanyName "CRONUS USA, Inc." -Verbose
    #>
    [CmdletBinding()]
    param(
        [Parameter(Mandatory = $true, Position = 0, HelpMessage = "Path to the .app file to publish")]
        [ValidateScript({
            if (-not (Test-Path $_ -PathType Leaf)) {
                throw "App file not found: $_"
            }
            if (-not $_.EndsWith('.app', [StringComparison]::OrdinalIgnoreCase)) {
                throw "File must have .app extension: $_"
            }
            $true
        })]
        [string]$AppFile,

        [Parameter(Mandatory = $true, Position = 1, HelpMessage = "Name of the Business Central environment")]
        [string]$EnvironmentName,

        [Parameter(Mandatory = $false, Position = 2, HelpMessage = "Tenant ID (default: default)")]
        [string]$Tenant = "default",

        [Parameter(Mandatory = $false, HelpMessage = "Company name for the app installation")]
        [string]$CompanyName,

        [Parameter(Mandatory = $false, HelpMessage = "Force publish without confirmation")]
        [switch]$Force
    )

    begin {
        Write-Verbose "Starting Publish-KritD365SalesApp"
        Write-Verbose "  AppFile: $AppFile"
        Write-Verbose "  EnvironmentName: $EnvironmentName"
        Write-Verbose "  Tenant: $Tenant"
        Write-Verbose "  CompanyName: $CompanyName"
        Write-Verbose "  Force: $Force"

        $result = [PSCustomObject]@{
            Success      = $false
            AppFile      = $AppFile
            Environment  = $EnvironmentName
            Tenant       = $Tenant
            CompanyName  = $CompanyName
            PublishedAt  = $null
            Message      = $null
            Method       = $null
            ErrorDetails = $null
        }

        $bcContainerHelperAvailable = $null -ne (Get-Module -ListAvailable -Name BcContainerHelper -ErrorAction SilentlyContinue)
        Write-Verbose "BcContainerHelper available: $bcContainerHelperAvailable"
    }

    process {
        try {
            if ($bcContainerHelperAvailable) {
                Write-Verbose "Using BcContainerHelper method"

                $publishParams = @{
                    appFile        = $AppFile
                    environmentName = $EnvironmentName
                    tenant         = $Tenant
                    skipVerification = $false
                }

                if ($Force) {
                    $publishParams.Force = $true
                }

                if (-not [string]::IsNullOrWhiteSpace($CompanyName)) {
                    $publishParams.companyName = $CompanyName
                }

                Write-Verbose "Calling Publish-BcContainerApp..."
                $publishResult = Publish-BcContainerApp @publishParams -ErrorAction Stop
                Write-Verbose "Publish completed: $($publishResult | Out-String)"

                Write-Verbose "Calling Sync-BcContainerApp..."
                $syncParams = @{
                    appFile        = $AppFile
                    environmentName = $EnvironmentName
                    tenant         = $Tenant
                }

                if (-not [string]::IsNullOrWhiteSpace($CompanyName)) {
                    $syncParams.companyName = $CompanyName
                }

                $syncResult = Sync-BcContainerApp @syncParams -ErrorAction Stop
                Write-Verbose "Sync completed: $($syncResult | Out-String)"

                Write-Verbose "Calling Install-BcContainerApp..."
                $installParams = @{
                    appFile        = $AppFile
                    environmentName = $EnvironmentName
                    tenant         = $Tenant
                }

                if ($Force) {
                    $installParams.Force = $true
                }

                if (-not [string]::IsNullOrWhiteSpace($CompanyName)) {
                    $installParams.companyName = $CompanyName
                }

                $installResult = Install-BcContainerApp @installParams -ErrorAction Stop
                Write-Verbose "Install completed: $($installResult | Out-String)"

                $result.Success = $true
                $result.PublishedAt = Get-Date -Format "o"
                $result.Message = "App published, synced, and installed successfully via BcContainerHelper"
                $result.Method = "BcContainerHelper"
            }
            else {
                Write-Verbose "Using BC Admin API fallback method"

                $apiVersion = "v2.3"
                $baseUrl = "https://api.businesscenter.telemetry.dynamics.com"

                Write-Verbose "Retrieving environment information..."
                $environments = Get-BcEnvironments -includeAPIBasedEnvInfo -ErrorAction SilentlyContinue
                $targetEnv = $environments | Where-Object { $_.EnvironmentName -eq $EnvironmentName }

                if (-not $targetEnv) {
                    throw "Environment '$EnvironmentName' not found. Available environments: $($environments.EnvironmentName -join ', ')"
                }

                $apiGatewayUrl = $targetEnv.ApiGatewayUrl
                if ([string]::IsNullOrWhiteSpace($apiGatewayUrl)) {
                    $apiGatewayUrl = $targetEnv.AadTenantId
                }

                $uploadUrl = "$apiGatewayUrl/admin/$apiVersion/applications/upload"

                Write-Verbose "Upload URL: $uploadUrl"

                $boundary = [guid]::NewGuid().ToString()
                $fileBytes = [System.IO.File]::ReadAllBytes($AppFile)
                $fileName = [System.IO.Path]::GetFileName($AppFile)

                $bodyParts = @()
                $bodyParts += "--$boundary`r`n"
                $bodyParts += "Content-Disposition: form-data; name=`"appFile`"; filename=`"$fileName`"`r`n"
                $bodyParts += "Content-Type: application/octet-stream`r`n`r`n"
                $bodyParts += [System.Text.Encoding]::UTF8.GetString($fileBytes)
                $bodyParts += "`r`n"
                $bodyParts += "--$boundary`r`n"
                $bodyParts += "Content-Disposition: form-data; name=`"environmentName`"`r`n`r`n"
                $bodyParts += $EnvironmentName
                $bodyParts += "`r`n"
                $bodyParts += "--$boundary`r`n"
                $bodyParts += "Content-Disposition: form-data; name=`"tenant`"`r`n`r`n"
                $bodyParts += $Tenant
                $bodyParts += "`r`n"

                if (-not [string]::IsNullOrWhiteSpace($CompanyName)) {
                    $bodyParts += "--$boundary`r`n"
                    $bodyParts += "Content-Disposition: form-data; name=`"companyName`"`r`n`r`n"
                    $bodyParts += $CompanyName
                    $bodyParts += "`r`n"
                }

                if ($Force) {
                    $bodyParts += "--$boundary`r`n"
                    $bodyParts += "Content-Disposition: form-data; name=`"force`"`r`n`r`n"
                    $bodyParts += "true"
                    $bodyParts += "`r`n"
                }

                $bodyParts += "--$boundary--`r`n"
                $body = $bodyParts -join ""

                $headers = @{
                    "Content-Type" = "multipart/form-data; boundary=$boundary"
                }

                Write-Verbose "Uploading app via BC Admin API..."
                try {
                    $uploadResponse = Invoke-RestMethod -Uri $uploadUrl -Method Post -Headers $headers -Body $body -ContentType "multipart/form-data; boundary=$boundary" -ErrorAction Stop
                    Write-Verbose "Upload response: $($uploadResponse | Out-String)"
                }
                catch {
                    $errorDetail = "BC Admin API upload failed: $($_.Exception.Message)"
                    Write-Warning $errorDetail
                    throw $errorDetail
                }

                $result.Success = $true
                $result.PublishedAt = Get-Date -Format "o"
                $result.Message = "App published successfully via BC Admin API"
                $result.Method = "BCAdminApi"
            }
        }
        catch {
            $result.Success = $false
            $result.PublishedAt = Get-Date -Format "o"
            $result.Message = "Failed to publish app"
            $result.ErrorDetails = $_.Exception.Message
            Write-Verbose "Error: $($_.Exception.Message)"
            Write-Verbose "Stack trace: $($_.ScriptStackTrace)"
        }
    }

    end {
        Write-Verbose "Completed Publish-KritD365SalesApp"
        Write-Verbose "Result: $($result | Out-String)"
        return $result
    }
}